export * from './Header/Header';
export * from './Movie/Movie';
export * from './MoviesDetails/MoviesDetails';
export * from './Pagination/Pagination';
export * from './Genres/Genres';
export * from './Genre/Genre';
export * from './StarsRating/StarsRating';
export * from './Theme/theme';
export * from './UserInfo/UserInfo';
